//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class kanban_columns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kanban_columns()
        {
            this.kanban_task = new HashSet<kanban_task>();
        }
    
        public int ID { get; set; }
        public int COLUMN_POS { get; set; }
        public string NAME { get; set; }
        public int ID_BOARD { get; set; }
    
        public virtual kanban_board kanban_board { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kanban_task> kanban_task { get; set; }
    }
}
