//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class kanban_task
    {
        public int ID_TASK { get; set; }
        public string TASK_NAME { get; set; }
        public string TASK_DESCRIPTION { get; set; }
        public int ID_COLUMN { get; set; }
    
        public virtual kanban_columns kanban_columns { get; set; }
    }
}
