//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanbanBoard.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QKOLA01_VSE_DBEntities : DbContext
    {
        public QKOLA01_VSE_DBEntities()
            : base("name=QKOLA01_VSE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kanban_board> kanban_board { get; set; }
        public virtual DbSet<kanban_columns> kanban_columns { get; set; }
        public virtual DbSet<kanban_task> kanban_task { get; set; }
    }
}
